on:
  push:
    branches:
      - main
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
      
    - name: âš™ Set Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
    
    - name: ğŸˆ yarn install
      uses: Borales/actions-yarn@v4
      with:
        cmd: install
      
    - name: ğŸ‘©â€ğŸ”§ yarn build
      uses: Borales/actions-yarn@v4
      with:
        cmd: build
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.opentechne.com
        username: opentechne@opentechne.com
        password: ${{ secrets.ftp_password }}
        local-dir: ./out/
